//! kree's egui palette, mapped from the user's nugu theme. The source of
//! truth is `~/Workspaces/dotfiles/nugu/output/dark.toml` (generated by
//! `just build` from `nugu.nu` + `palette.nu`).
//!
//! Mapping conventions:
//!
//! | nugu                          | egui slot                          |
//! |-------------------------------|------------------------------------|
//! | ui.backdrop                   | window_fill / panel_fill           |
//! | content.backdrop              | extreme_bg_color (popup body)      |
//! | ui.normal                     | default text via fg_stroke         |
//! | ui.minor                      | weak / disabled text               |
//! | ui.unfocus                    | inactive widget fill               |
//! | ui.accent                     | hover / active widget fill         |
//! | ui.focus                      | selection background, focus stroke |
//! | ui.important_local            | active fg, link hover              |
//! | ui.important_global           | hover fg                           |
//! | palette.error                 | error_fg_color                     |
//! | palette.warning               | warn_fg_color                      |
//! | palette.info                  | hyperlink_color                    |
//!
//! `apply` is idempotent — `App::ui` re-asserts visuals every frame, and
//! every popup viewport re-applies it inside its closure (each viewport
//! owns its own egui `Context`).

use eframe::egui::{self, Color32, CornerRadius, Stroke, Visuals};

// palette.* (top-level)
const ERROR: Color32 = Color32::from_rgb(0xe4, 0x64, 0x79);
const WARN: Color32 = Color32::from_rgb(0x9e, 0x9a, 0x69);
const INFO: Color32 = Color32::from_rgb(0x3e, 0xc5, 0xdd);

// palette.ui (chrome)
const UI_NORMAL: Color32 = Color32::from_rgb(0xdb, 0xdb, 0xdb);
const UI_BACKDROP: Color32 = Color32::from_rgb(0x24, 0x24, 0x24);
const UI_ACCENT: Color32 = Color32::from_rgb(0xd8, 0x6d, 0xd8);
const UI_MINOR: Color32 = Color32::from_rgb(0x9d, 0x9d, 0x9d);
const UI_FOCUS: Color32 = Color32::from_rgb(0x9a, 0xab, 0xae);
const UI_UNFOCUS: Color32 = Color32::from_rgb(0x6f, 0x6f, 0x6f);
const UI_IMPORTANT_LOCAL: Color32 = Color32::from_rgb(0xc9, 0xb6, 0xeb);
const UI_IMPORTANT_GLOBAL: Color32 = Color32::from_rgb(0xf3, 0xef, 0xfb);

// palette.content (popup body — slightly more contrast than UI chrome)
const CONTENT_BACKDROP: Color32 = Color32::from_rgb(0x12, 0x12, 0x12);

pub fn apply(ctx: &egui::Context) {
    let mut v = Visuals::dark();

    v.window_fill = UI_BACKDROP;
    v.panel_fill = UI_BACKDROP;
    v.extreme_bg_color = CONTENT_BACKDROP;
    v.faint_bg_color = Color32::from_rgb(0x2c, 0x2c, 0x2c); // halfway to ui.unfocus
    v.code_bg_color = CONTENT_BACKDROP;
    v.window_stroke = Stroke::new(1.0, UI_UNFOCUS);

    v.error_fg_color = ERROR;
    v.warn_fg_color = WARN;
    v.hyperlink_color = INFO;

    v.selection.bg_fill = UI_FOCUS;
    v.selection.stroke = Stroke::new(1.0, UI_IMPORTANT_LOCAL);

    let radius = CornerRadius::same(3);
    let widgets = &mut v.widgets;

    widgets.noninteractive.bg_fill = UI_BACKDROP;
    widgets.noninteractive.weak_bg_fill = UI_BACKDROP;
    widgets.noninteractive.fg_stroke = Stroke::new(1.0, UI_NORMAL);
    widgets.noninteractive.bg_stroke = Stroke::new(1.0, UI_UNFOCUS);
    widgets.noninteractive.corner_radius = radius;

    widgets.inactive.bg_fill = UI_UNFOCUS;
    widgets.inactive.weak_bg_fill = Color32::from_rgb(0x35, 0x35, 0x35);
    widgets.inactive.fg_stroke = Stroke::new(1.0, UI_NORMAL);
    widgets.inactive.bg_stroke = Stroke::new(1.0, UI_MINOR);
    widgets.inactive.corner_radius = radius;

    widgets.hovered.bg_fill = UI_ACCENT;
    widgets.hovered.weak_bg_fill = UI_FOCUS;
    widgets.hovered.fg_stroke = Stroke::new(1.5, UI_IMPORTANT_GLOBAL);
    widgets.hovered.bg_stroke = Stroke::new(1.5, UI_IMPORTANT_LOCAL);
    widgets.hovered.corner_radius = radius;

    widgets.active.bg_fill = UI_IMPORTANT_LOCAL;
    widgets.active.weak_bg_fill = UI_ACCENT;
    widgets.active.fg_stroke = Stroke::new(1.5, UI_BACKDROP);
    widgets.active.bg_stroke = Stroke::new(1.5, UI_IMPORTANT_GLOBAL);
    widgets.active.corner_radius = radius;

    widgets.open.bg_fill = UI_FOCUS;
    widgets.open.fg_stroke = Stroke::new(1.0, UI_IMPORTANT_GLOBAL);
    widgets.open.bg_stroke = Stroke::new(1.0, UI_ACCENT);
    widgets.open.corner_radius = radius;

    ctx.set_visuals(v);
}
