//! kree's egui palette, mapped from the user's nugu theme. The source of
//! truth is `~/Workspaces/dotfiles/nugu/output/dark.toml` (generated by
//! `just build` from `nugu.nu` + `palette.nu`).
//!
//! Mapping conventions:
//!
//! | nugu                          | egui slot                          |
//! |-------------------------------|------------------------------------|
//! | ui.backdrop                   | window_fill / panel_fill           |
//! | content.backdrop              | extreme_bg_color (popup body)      |
//! | ui.normal                     | default text via fg_stroke         |
//! | ui.minor                      | weak / disabled text               |
//! | ui.unfocus                    | inactive widget fill               |
//! | ui.accent                     | hover / active widget fill         |
//! | ui.focus                      | selection background, focus stroke |
//! | ui.important_local            | active fg, link hover              |
//! | ui.important_global           | hover fg                           |
//! | palette.error                 | error_fg_color                     |
//! | palette.warning               | warn_fg_color                      |
//! | palette.info                  | hyperlink_color                    |
//!
//! `apply` is idempotent — `App::ui` re-asserts visuals every frame, and
//! every popup viewport re-applies it inside its closure (each viewport
//! owns its own egui `Context`).

use std::sync::Arc;

use eframe::egui::{
    self, Color32, CornerRadius, FontData, FontDefinitions, FontFamily, FontId, Stroke, TextStyle,
    Visuals,
};
use tracing::{info, warn};

// palette.* (top-level)
const ERROR: Color32 = Color32::from_rgb(0xe4, 0x64, 0x79);
const WARN: Color32 = Color32::from_rgb(0x9e, 0x9a, 0x69);
const INFO: Color32 = Color32::from_rgb(0x3e, 0xc5, 0xdd);

// palette.ui (chrome)
const UI_NORMAL: Color32 = Color32::from_rgb(0xdb, 0xdb, 0xdb);
const UI_BACKDROP: Color32 = Color32::from_rgb(0x24, 0x24, 0x24);
const UI_ACCENT: Color32 = Color32::from_rgb(0xd8, 0x6d, 0xd8);
const UI_MINOR: Color32 = Color32::from_rgb(0x9d, 0x9d, 0x9d);
const UI_FOCUS: Color32 = Color32::from_rgb(0x9a, 0xab, 0xae);
const UI_UNFOCUS: Color32 = Color32::from_rgb(0x6f, 0x6f, 0x6f);
const UI_IMPORTANT_LOCAL: Color32 = Color32::from_rgb(0xc9, 0xb6, 0xeb);
const UI_IMPORTANT_GLOBAL: Color32 = Color32::from_rgb(0xf3, 0xef, 0xfb);

// palette.content (popup body — slightly more contrast than UI chrome)
const CONTENT_BACKDROP: Color32 = Color32::from_rgb(0x12, 0x12, 0x12);

// Bundled JetBrains Mono Nerd Font (Mono variant, Regular). Source:
// https://github.com/ryanoasis/nerd-fonts/releases — OFL-1.1 licensed.
// Single-cell ("Mono") variant chosen so monospace columns line up.
const JETBRAINS_MONO_NF: &[u8] =
    include_bytes!("../assets/fonts/JetBrainsMonoNerdFontMono-Regular.ttf");

/// Register fonts with egui:
///
/// 1. JetBrains Mono Nerd Font (bundled) — primary monospace, plus
///    fallback for the proportional family so headings get nerd glyphs.
/// 2. Segoe UI Variable / Segoe UI from `C:\Windows\Fonts\` — primary
///    proportional. Always present on Win10/11.
/// 3. Cascadia Mono / Code, Segoe UI Emoji / Symbol / Icons —
///    additional fallbacks for the gaps.
///
/// Call once at app startup. `set_fonts` rebuilds the font atlas, so
/// don't put it in the per-frame path. Fonts that fail to load are
/// skipped with a warning; egui's bundled defaults take over.
pub fn install_fonts(ctx: &egui::Context) {
    let mut fonts = FontDefinitions::default();

    // Bundled — always present.
    fonts.font_data.insert(
        "jetbrains-mono-nf".into(),
        Arc::new(FontData::from_static(JETBRAINS_MONO_NF)),
    );

    let candidates: &[(&str, &str)] = &[
        ("segoe-ui-variable", r"C:\Windows\Fonts\SegUIVar.ttf"),
        ("segoe-ui", r"C:\Windows\Fonts\segoeui.ttf"),
        ("cascadia-mono", r"C:\Windows\Fonts\CascadiaMono.ttf"),
        ("cascadia-code", r"C:\Windows\Fonts\CascadiaCode.ttf"),
        ("segoe-emoji", r"C:\Windows\Fonts\seguiemj.ttf"),
        ("segoe-symbol", r"C:\Windows\Fonts\seguisym.ttf"),
        ("segoe-icons", r"C:\Windows\Fonts\SegoeIcons.ttf"),
    ];

    let mut loaded = vec!["jetbrains-mono-nf"];
    for (name, path) in candidates {
        match std::fs::read(path) {
            Ok(bytes) => {
                fonts
                    .font_data
                    .insert((*name).into(), Arc::new(FontData::from_owned(bytes)));
                loaded.push(*name);
            }
            Err(e) => warn!(font = name, path, error = %e, "system font missing; skipping"),
        }
    }
    info!(?loaded, "fonts loaded");

    if let Some(family) = fonts.families.get_mut(&FontFamily::Proportional) {
        for primary in ["segoe-ui-variable", "segoe-ui"] {
            if fonts.font_data.contains_key(primary) {
                family.insert(0, primary.into());
                break;
            }
        }
        // Append Nerd Font + symbol / emoji fallbacks so glyphs missing
        // in Segoe UI flow through to something that has them.
        for fallback in [
            "jetbrains-mono-nf",
            "segoe-icons",
            "segoe-symbol",
            "segoe-emoji",
        ] {
            if fonts.font_data.contains_key(fallback) {
                family.push(fallback.into());
            }
        }
    }
    if let Some(family) = fonts.families.get_mut(&FontFamily::Monospace) {
        family.insert(0, "jetbrains-mono-nf".into());
        for fallback in ["cascadia-mono", "cascadia-code"] {
            if fonts.font_data.contains_key(fallback) {
                family.push(fallback.into());
            }
        }
        for fallback in ["segoe-icons", "segoe-symbol", "segoe-emoji"] {
            if fonts.font_data.contains_key(fallback) {
                family.push(fallback.into());
            }
        }
    }

    ctx.set_fonts(fonts);
}

fn apply_text_styles(ctx: &egui::Context) {
    ctx.all_styles_mut(|style| {
        style.text_styles.insert(
            TextStyle::Heading,
            FontId::new(26.0, FontFamily::Proportional),
        );
        style
            .text_styles
            .insert(TextStyle::Body, FontId::new(15.0, FontFamily::Proportional));
        style.text_styles.insert(
            TextStyle::Button,
            FontId::new(15.0, FontFamily::Proportional),
        );
        style.text_styles.insert(
            TextStyle::Monospace,
            FontId::new(14.0, FontFamily::Monospace),
        );
        style.text_styles.insert(
            TextStyle::Small,
            FontId::new(12.0, FontFamily::Proportional),
        );
    });
}

pub fn apply(ctx: &egui::Context) {
    apply_text_styles(ctx);
    let mut v = Visuals::dark();

    v.window_fill = UI_BACKDROP;
    v.panel_fill = UI_BACKDROP;
    v.extreme_bg_color = CONTENT_BACKDROP;
    v.faint_bg_color = Color32::from_rgb(0x2c, 0x2c, 0x2c); // halfway to ui.unfocus
    v.code_bg_color = CONTENT_BACKDROP;
    v.window_stroke = Stroke::new(1.0, UI_UNFOCUS);

    v.error_fg_color = ERROR;
    v.warn_fg_color = WARN;
    v.hyperlink_color = INFO;

    v.selection.bg_fill = UI_FOCUS;
    v.selection.stroke = Stroke::new(1.0, UI_IMPORTANT_LOCAL);

    let radius = CornerRadius::same(3);
    let widgets = &mut v.widgets;

    widgets.noninteractive.bg_fill = UI_BACKDROP;
    widgets.noninteractive.weak_bg_fill = UI_BACKDROP;
    widgets.noninteractive.fg_stroke = Stroke::new(1.0, UI_NORMAL);
    widgets.noninteractive.bg_stroke = Stroke::new(1.0, UI_UNFOCUS);
    widgets.noninteractive.corner_radius = radius;

    widgets.inactive.bg_fill = UI_UNFOCUS;
    widgets.inactive.weak_bg_fill = Color32::from_rgb(0x35, 0x35, 0x35);
    widgets.inactive.fg_stroke = Stroke::new(1.0, UI_NORMAL);
    widgets.inactive.bg_stroke = Stroke::new(1.0, UI_MINOR);
    widgets.inactive.corner_radius = radius;

    widgets.hovered.bg_fill = UI_ACCENT;
    widgets.hovered.weak_bg_fill = UI_FOCUS;
    widgets.hovered.fg_stroke = Stroke::new(1.5, UI_IMPORTANT_GLOBAL);
    widgets.hovered.bg_stroke = Stroke::new(1.5, UI_IMPORTANT_LOCAL);
    widgets.hovered.corner_radius = radius;

    widgets.active.bg_fill = UI_IMPORTANT_LOCAL;
    widgets.active.weak_bg_fill = UI_ACCENT;
    widgets.active.fg_stroke = Stroke::new(1.5, UI_BACKDROP);
    widgets.active.bg_stroke = Stroke::new(1.5, UI_IMPORTANT_GLOBAL);
    widgets.active.corner_radius = radius;

    widgets.open.bg_fill = UI_FOCUS;
    widgets.open.fg_stroke = Stroke::new(1.0, UI_IMPORTANT_GLOBAL);
    widgets.open.bg_stroke = Stroke::new(1.0, UI_ACCENT);
    widgets.open.corner_radius = radius;

    ctx.set_visuals(v);
}
